services:
  ai-app:
    container_name: ai-app
    build: .
    working_dir: /code/app
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    restart: always
    environment:
      APP_NAME: ${APP_TITLE}
      APP_DESCRIPTION: ${DESCRIPTION}
      API_PREFIX: ${API_PREFIX}
      REDIS_ENDPOINT: ${REDIS_ENDPOINT}
      REDIS_PORT: ${REDIS_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_TABLE: ${AWS_TABLE}
      MONGO_URI: ${MONGO_URI}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

  ai-app-redis:
    image: redis:alpine
    container_name: ai-app-redis